#!/usr/bin/env bash
# ============================================================================
# 01_dump.sh — dump the OLD (live, rhs-band) Supabase project.
# ----------------------------------------------------------------------------
# TARGET: OLD — READ-ONLY (dumps and counts only; the live app is untouched).
#
# Produces (all under scripts/migrate/out/, gitignored, created with umask 077):
#   roles.sql              --role-only role definitions
#   schema.sql             schema-only (tables, RLS, RPCs, triggers)
#   data.sql               data-only with COPY: all public rows + auth.users
#                          (password hashes) + auth.identities + storage rows
#                          (sensitive, local only). Platform session state
#                          (auth.sessions/refresh_tokens/…) is NOT dumped.
#   migrations_history.csv supabase_migrations.schema_migrations contents
#   row_counts_old.txt     per-table baseline for 05_verify.sh
#   attendance_checksum_old.txt  fingerprint of attendance history
#
# Idempotent: safe to re-run; files are overwritten in place.
#
# Requirements: psql + pg_dump (PostgreSQL client tools). Portable copies in
# .tools/pgsql/bin are picked up automatically by lib.sh.
# Tooling note: the Supabase CLI's `db dump` shells out to Docker on machines
# without the local stack (CLI 2.119 on Windows), which we can't install here.
# We call pg_dump 18 — the exact engine the CLI wraps — with the same modes
# (--schema-only / --data-only, COPY output is the plain-format default), and
# generate idempotent role DDL via SQL instead of `--role-only`.
# Env: OLD_DB_URL (see .env). Values are never printed.
# ============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
load_env
require_vars OLD_DB_URL
mkdir -p "$OUT_DIR"
umask 077

banner "TARGET: OLD project (live RHS Band) — READ-ONLY (dumps and counts only)" \
  "Dumping roles, schema, data, migration history and baseline counts to scripts/migrate/out/"

need_cmd psql     "PostgreSQL client"
need_cmd pg_dump  "ships with PostgreSQL client tools"

log "roles.sql (idempotent guarded CREATE ROLE for non-system roles) …"
{
  printf -- '-- Generated by 01_dump.sh — idempotent role recreation (no passwords).\n'
  psql "$OLD_DB_URL" -X -At -v ON_ERROR_STOP=1 <<'SQL'
select format(
  'do $$ begin if not exists (select 1 from pg_roles where rolname = %L) then create role %I %s; end if; end $$;',
  r.rolname,
  r.rolname,
  case when r.rolcanlogin then 'login' else 'nologin' end
)
  from pg_catalog.pg_roles r
 where r.rolname not like 'pg\_%'
 order by r.rolname;
SQL
} > "$OUT_DIR/roles.sql"

# Supabase-owned schemas (auth, storage, realtime, …) already exist on the NEW
# project with platform-managed structure; recreating them from the dump would
# fail (CREATE SCHEMA auth … ) or drift across platform versions. So schema.sql
# is intentionally PUBLIC-ONLY. The app's custom bits that live on those
# schemas (handle_new_user + signup trigger, avatars bucket + policies) are
# recreated idempotently from sql/reapply_auth_storage.sql inside
# 02_restore.sh, and 03_auth_storage.sh captures the auth/storage schema
# separately for old-vs-new diffing.
log "schema.sql (public schema only, --no-owner) …"
pg_dump "$OLD_DB_URL" --schema-only --no-owner \
  --exclude-schema=auth --exclude-schema=storage --exclude-schema=realtime \
  --exclude-schema=supabase_migrations --exclude-schema=extensions \
  --exclude-schema=graphql --exclude-schema=graphql_public \
  --exclude-schema=pgbouncer --exclude-schema=vault \
  --exclude-schema=pgsodium --exclude-schema=pgsodium_masks \
  --exclude-schema=cron --exclude-schema=net --exclude-schema=pgmq \
  -f "$OUT_DIR/schema.sql"

# pg_dump cannot exclude DATABASE-LEVEL objects via --exclude-schema, so the raw
# dump still carries the platform's event triggers (ensure_rls, pgrst_*, issue_*)
# and the public.rls_auto_enable() function Supabase ships with them. NEW already
# defines all of them; creating them again fails with "already exists" (and they
# are NOT ours to own). Strip them from schema.sql. Keep in sync with
# sql/reset_public.sql, which preserves rls_auto_enable() on re-runs.
# Platform-owned objects still present: event triggers (ensure_rls, pgrst_*,
# issue_*), the rls_auto_enable() function, publications (supabase_realtime*),
# the realtime.messages publication membership, ACLs on extension/platform
# functions (signature-drift risk across platform versions), and
# ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin (postgres cannot run those).
# Strip all of it. KEEP: app-table publication memberships (public.*) and all
# public-schema ACLs — those are the app's own.
sed \
  -e '/^-- Name: .*; Type: EVENT TRIGGER/,/;$/d' \
  -e '/^-- Name: rls_auto_enable()/,/^\$\$;$/d' \
  -e '/^-- Name: FUNCTION rls_auto_enable(); Type: ACL/,/;$/d' \
  -e '/^\(GRANT\|REVOKE\) .*rls_auto_enable/d' \
  -e '/^ALTER EVENT TRIGGER/d' \
  -e '/^-- Name: supabase_realtime; Type: PUBLICATION;/,/;$/d' \
  -e '/^-- Name: supabase_realtime_messages_publication; Type: PUBLICATION;/,/;$/d' \
  -e '/^-- Name: supabase_realtime_messages_publication messages; Type: PUBLICATION TABLE/,/;$/d' \
  -e '/^-- Name: .*; Type: DEFAULT ACL/,/;$/d' \
  -e '/^ALTER DEFAULT PRIVILEGES/d' \
  -e '/^CREATE PUBLICATION/d' \
  -e '/^\(GRANT\|REVOKE\) .*\(extensions\|vault\|pg_catalog\|realtime\|auth\|storage\)\./d' \
  -e '/rls_auto_enable/d' \
  -e 's/^\(REVOKE ALL ON \(FUNCTION\|TABLE\|SEQUENCE\|TYPE\) public\.[^;]*\) FROM PUBLIC;/\1 FROM PUBLIC, anon, authenticated, service_role;/' \
  "$OUT_DIR/schema.sql" > "$OUT_DIR/schema.sql.tmp"
mv "$OUT_DIR/schema.sql.tmp" "$OUT_DIR/schema.sql"
if grep -qE 'EVENT TRIGGER|rls_auto_enable|CREATE PUBLICATION|ALTER DEFAULT PRIVILEGES' "$OUT_DIR/schema.sql"; then
  die "schema.sql still contains platform-owned objects after filtering — refusing to continue."
fi
[[ "$(grep -c '^ALTER PUBLICATION supabase_realtime ADD TABLE ONLY public\.' "$OUT_DIR/schema.sql")" -eq 3 ]] \
  || die "schema.sql lost the app's realtime publication memberships — refusing to continue."
# Guard against a broken filter eating the app's own objects (this happened
# once: an over-greedy sed range truncated the file to EOF).
[[ "$(grep -c '^CREATE TABLE' "$OUT_DIR/schema.sql")" -ge 13 ]] \
  || die "schema.sql filter ate app tables (CREATE TABLE count too low) — refusing to continue."
[[ "$(grep -c '^CREATE FUNCTION public\.' "$OUT_DIR/schema.sql")" -ge 30 ]] \
  || die "schema.sql filter ate app functions (CREATE FUNCTION count too low) — refusing to continue."

# Data: every public row + exactly the platform rows the clone needs —
# auth.users (password hashes) + auth.identities for sign-in continuity and the
# Clerk import, storage.buckets/objects for avatars. Live platform session
# state (auth.sessions, refresh_tokens, one_time_tokens, mfa_*, …) is
# deliberately NOT copied: it is runtime state, useless and sensitive on the
# other side. Old-platform → new-platform copies are safe because pg_dump
# always emits explicit column lists (old columns are a subset of new ones).
log "data.sql (data-only: public + auth.users/identities + storage rows) …"
pg_dump "$OLD_DB_URL" --data-only --schema=public > "$OUT_DIR/data.sql"
pg_dump "$OLD_DB_URL" --data-only \
  --table=auth.users --table=auth.identities \
  --table=storage.buckets --table=storage.objects \
  >> "$OUT_DIR/data.sql"

log "migrations_history.csv (supabase_migrations.schema_migrations) …"
# COPY TO STDOUT is server-side and read-only; the psql \copy meta-command is
# not usable under -c, so we stream the query result to a file instead.
if ! psql "$OLD_DB_URL" -X -v ON_ERROR_STOP=1 -A -F',' \
      -c "copy (select * from supabase_migrations.schema_migrations order by 1) to stdout with header csv" \
      > "$OUT_DIR/migrations_history.csv"; then
  warn "supabase_migrations.schema_migrations not readable — record migration history manually (Dashboard → Database → Migrations)."
fi

log "Baseline row counts …"
collect_row_counts "$OLD_DB_URL" "$OUT_DIR/row_counts_old.txt"

log "Attendance history fingerprint …"
attendance_checksum "$OLD_DB_URL" > "$OUT_DIR/attendance_checksum_old.txt"

log "Dump complete. Contents of scripts/migrate/out/:"
ls -la "$OUT_DIR" | sed 's/^/    /'
log "NOTE: data.sql contains password hashes — out/ is gitignored; never commit or share it."
